name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #- name: Setup Java JDK
    #  uses: actions/setup-java@v1.3.0
    #  with:
    #    java-version: 1.8
    #- uses: actions/checkout@v2
    #- name: Build Java dependency
    #  run: make build-java
    #- name: Build
    #  run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
